name: Kubernetes manifests

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up cue
        uses: cue-lang/setup-cue@v0.0.1

      - name: validate manifests
        run: cue vet examples/nginx-deployment.yaml examples/nginx-deployment.cue
